/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApiTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'name', 'token', 'type', 'updatedAt', 'usersId'] as const
  $columns = ApiTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare token: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usersId: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BucketSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt', 'visibility'] as const
  $columns = BucketSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visibility: string
}

export class CarouselSchema extends BaseModel {
  static $columns = ['buttonContent', 'buttonUrl', 'content', 'createdAt', 'id', 'imageFilesId', 'logoFilesId', 'title', 'updatedAt'] as const
  $columns = CarouselSchema.$columns
  @column()
  declare buttonContent: string | null
  @column()
  declare buttonUrl: string | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageFilesId: number
  @column()
  declare logoFilesId: number | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FileSchema extends BaseModel {
  static $columns = ['bucketsId', 'createdAt', 'id', 'pathfilename', 'size', 'updatedAt', 'url'] as const
  $columns = FileSchema.$columns
  @column()
  declare bucketsId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pathfilename: string
  @column()
  declare size: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}

export class GameSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'developer', 'gameConfigurationsMinimalId', 'gameConfigurationsRecommendedId', 'gameMode', 'id', 'logoFilesId', 'newGame', 'pegiRating', 'pictureFilesId', 'publisher', 'releaseDate', 'title', 'trailerFilesId', 'upcomingGame', 'updatedAt'] as const
  $columns = GameSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare developer: string
  @column()
  declare gameConfigurationsMinimalId: number | null
  @column()
  declare gameConfigurationsRecommendedId: number | null
  @column()
  declare gameMode: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logoFilesId: number
  @column()
  declare newGame: boolean | null
  @column()
  declare pegiRating: string
  @column()
  declare pictureFilesId: number
  @column()
  declare publisher: string
  @column.dateTime()
  declare releaseDate: DateTime | null
  @column()
  declare title: string
  @column()
  declare trailerFilesId: number
  @column()
  declare upcomingGame: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameBinarySchema extends BaseModel {
  static $columns = ['createdAt', 'filesId', 'gamePlatformsId', 'id', 'updatedAt'] as const
  $columns = GameBinarySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare filesId: number | null
  @column()
  declare gamePlatformsId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameBinaryAssignmentSchema extends BaseModel {
  static $columns = ['createdAt', 'gameBinariesId', 'gamesId', 'id', 'updatedAt'] as const
  $columns = GameBinaryAssignmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gameBinariesId: number | null
  @column()
  declare gamesId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = GameCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameCategoryAssignmentSchema extends BaseModel {
  static $columns = ['createdAt', 'gameCategoriesId', 'gamesId', 'id', 'updatedAt'] as const
  $columns = GameCategoryAssignmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gameCategoriesId: number | null
  @column()
  declare gamesId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameChangeLogSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'gamesId', 'id', 'releaseDate', 'updatedAt', 'version'] as const
  $columns = GameChangeLogSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gamesId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare releaseDate: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string
}

export class GameConfigurationSchema extends BaseModel {
  static $columns = ['additionalNotes', 'cpuAmd', 'cpuIntel', 'createdAt', 'gpuAmd', 'gpuNvidia', 'id', 'internet', 'os', 'ram', 'storage', 'type', 'updatedAt'] as const
  $columns = GameConfigurationSchema.$columns
  @column()
  declare additionalNotes: string | null
  @column()
  declare cpuAmd: string
  @column()
  declare cpuIntel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gpuAmd: string
  @column()
  declare gpuNvidia: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare internet: boolean | null
  @column()
  declare os: string
  @column()
  declare ram: string
  @column()
  declare storage: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameLanguageSchema extends BaseModel {
  static $columns = ['createdAt', 'gamesId', 'id', 'languagesId', 'updatedAt'] as const
  $columns = GameLanguageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gamesId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare languagesId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameMediaSchema extends BaseModel {
  static $columns = ['createdAt', 'filesId', 'gamesId', 'id', 'type', 'updatedAt'] as const
  $columns = GameMediaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare filesId: number
  @column()
  declare gamesId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GamePlatformSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = GamePlatformSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GamePlatformAssignmentSchema extends BaseModel {
  static $columns = ['createdAt', 'gamePlatformsId', 'gamesId', 'id', 'updatedAt'] as const
  $columns = GamePlatformAssignmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gamePlatformsId: number | null
  @column()
  declare gamesId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameServerSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'region', 'updatedAt'] as const
  $columns = GameServerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare region: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameVersionSchema extends BaseModel {
  static $columns = ['createdAt', 'gamesId', 'id', 'isAvailable', 'updatedAt', 'version'] as const
  $columns = GameVersionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gamesId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAvailable: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string
}

export class LanguageSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = LanguageSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MaintenanceWebSiteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isMaintenance', 'name', 'updatedAt'] as const
  $columns = MaintenanceWebSiteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isMaintenance: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['createdAt', 'currency', 'id', 'paymentIntentId', 'statusOrder', 'totalPrice', 'updatedAt', 'usersId'] as const
  $columns = OrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare paymentIntentId: string | null
  @column()
  declare statusOrder: string
  @column()
  declare totalPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usersId: number | null
}

export class OrderMetadataStripeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'processedItems', 'updatedAt', 'usersId'] as const
  $columns = OrderMetadataStripeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare processedItems: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usersId: number | null
}

export class OrderProductSchema extends BaseModel {
  static $columns = ['createdAt', 'gameServersId', 'id', 'ordersId', 'price', 'productsId', 'quantity', 'updatedAt'] as const
  $columns = OrderProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gameServersId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ordersId: number | null
  @column()
  declare price: string
  @column()
  declare productsId: number | null
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'updatedAt', 'usersId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usersId: number | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'gamesId', 'id', 'imageFilesId', 'name', 'price', 'productCategoriesId', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare gamesId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageFilesId: number | null
  @column()
  declare name: string
  @column()
  declare price: string
  @column()
  declare productCategoriesId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = ProductCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductDiscountSchema extends BaseModel {
  static $columns = ['createdAt', 'currency', 'discountPercent', 'id', 'productsId', 'updatedAt'] as const
  $columns = ProductDiscountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string
  @column()
  declare discountPercent: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productsId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductGameServerSchema extends BaseModel {
  static $columns = ['createdAt', 'gameServersId', 'id', 'productsId', 'updatedAt'] as const
  $columns = ProductGameServerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gameServersId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productsId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StripeWebhookEventSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'stripeEventId', 'updatedAt'] as const
  $columns = StripeWebhookEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare stripeEventId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TicketSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'subject', 'ticketCategoriesId', 'ticketStatusesId', 'updatedAt', 'usersId'] as const
  $columns = TicketSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare subject: string
  @column()
  declare ticketCategoriesId: number | null
  @column()
  declare ticketStatusesId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usersId: number | null
}

export class TicketCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = TicketCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TicketResponseSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'isSupport', 'ticketsId', 'updatedAt', 'usersId'] as const
  $columns = TicketResponseSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSupport: boolean | null
  @column()
  declare ticketsId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usersId: number | null
}

export class TicketStatusSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = TicketStatusSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['activeCode', 'createdAt', 'currencyCode', 'email', 'id', 'ipAddress', 'ipRegion', 'isActive', 'password', 'rolesId', 'stripeCustomerId', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare activeCode: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currencyCode: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare ipRegion: string | null
  @column()
  declare isActive: boolean | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare rolesId: number | null
  @column()
  declare stripeCustomerId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}

export class UserGameLibrarySchema extends BaseModel {
  static $columns = ['createdAt', 'gamesId', 'id', 'updatedAt', 'usersId'] as const
  $columns = UserGameLibrarySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gamesId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usersId: number | null
}

export class UserGameWishlistSchema extends BaseModel {
  static $columns = ['createdAt', 'gamesId', 'id', 'updatedAt', 'usersId'] as const
  $columns = UserGameWishlistSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare gamesId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usersId: number
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
