apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: staging-crzgames-website-backend-hpa
  namespace: staging-crzgames-website-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: staging-crzgames-website-backend-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
