/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'health': {
    methods: ["GET","HEAD"],
    pattern: '/health',
    tokens: [{"old":"/health","type":0,"val":"health","end":""}],
    types: placeholder as Registry['health']['types'],
  },
  'auth.sign_up': {
    methods: ["POST"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['auth.sign_up']['types'],
  },
  'auth.sign_in': {
    methods: ["POST"],
    pattern: '/signin',
    tokens: [{"old":"/signin","type":0,"val":"signin","end":""}],
    types: placeholder as Registry['auth.sign_in']['types'],
  },
  'auth.sign_out': {
    methods: ["POST"],
    pattern: '/signout',
    tokens: [{"old":"/signout","type":0,"val":"signout","end":""}],
    types: placeholder as Registry['auth.sign_out']['types'],
  },
  'auth.verify_code': {
    methods: ["POST"],
    pattern: '/verify',
    tokens: [{"old":"/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['auth.verify_code']['types'],
  },
  'auth.forgot_password': {
    methods: ["POST"],
    pattern: '/forgot-password',
    tokens: [{"old":"/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['auth.forgot_password']['types'],
  },
  'auth.reset_password': {
    methods: ["POST"],
    pattern: '/reset-password',
    tokens: [{"old":"/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['auth.reset_password']['types'],
  },
  'auth.send_mail_to_modify_email': {
    methods: ["POST"],
    pattern: '/modify-email',
    tokens: [{"old":"/modify-email","type":0,"val":"modify-email","end":""}],
    types: placeholder as Registry['auth.send_mail_to_modify_email']['types'],
  },
  'auth.reset_email': {
    methods: ["POST"],
    pattern: '/reset-email',
    tokens: [{"old":"/reset-email","type":0,"val":"reset-email","end":""}],
    types: placeholder as Registry['auth.reset_email']['types'],
  },
  'auth.resend_new_code_verification_account': {
    methods: ["POST"],
    pattern: '/resend-code',
    tokens: [{"old":"/resend-code","type":0,"val":"resend-code","end":""}],
    types: placeholder as Registry['auth.resend_new_code_verification_account']['types'],
  },
  'carousel.get_all_carousels': {
    methods: ["GET","HEAD"],
    pattern: '/carousels',
    tokens: [{"old":"/carousels","type":0,"val":"carousels","end":""}],
    types: placeholder as Registry['carousel.get_all_carousels']['types'],
  },
  'carousel.get_carousel_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/carousel/:id',
    tokens: [{"old":"/carousel/:id","type":0,"val":"carousel","end":""},{"old":"/carousel/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['carousel.get_carousel_by_id']['types'],
  },
  'carousel.create_carousel': {
    methods: ["POST"],
    pattern: '/carousel',
    tokens: [{"old":"/carousel","type":0,"val":"carousel","end":""}],
    types: placeholder as Registry['carousel.create_carousel']['types'],
  },
  'carousel.update_carousel': {
    methods: ["PUT"],
    pattern: '/carousel/:id',
    tokens: [{"old":"/carousel/:id","type":0,"val":"carousel","end":""},{"old":"/carousel/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['carousel.update_carousel']['types'],
  },
  'carousel.delete': {
    methods: ["DELETE"],
    pattern: '/carousel/:id',
    tokens: [{"old":"/carousel/:id","type":0,"val":"carousel","end":""},{"old":"/carousel/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['carousel.delete']['types'],
  },
  'cloud_storage_s_3.get_all_buckets': {
    methods: ["GET","HEAD"],
    pattern: '/cloud-storage-s3/buckets',
    tokens: [{"old":"/cloud-storage-s3/buckets","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/buckets","type":0,"val":"buckets","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.get_all_buckets']['types'],
  },
  'cloud_storage_s_3.get_list_files_object_in_bucket': {
    methods: ["POST"],
    pattern: '/cloud-storage-s3/list-files',
    tokens: [{"old":"/cloud-storage-s3/list-files","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/list-files","type":0,"val":"list-files","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.get_list_files_object_in_bucket']['types'],
  },
  'cloud_storage_s_3.upload_file_or_folder_in_bucket': {
    methods: ["POST"],
    pattern: '/cloud-storage-s3/upload',
    tokens: [{"old":"/cloud-storage-s3/upload","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/upload","type":0,"val":"upload","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.upload_file_or_folder_in_bucket']['types'],
  },
  'cloud_storage_s_3.download_file_or_folder_in_bucket': {
    methods: ["GET","HEAD"],
    pattern: '/cloud-storage-s3/download',
    tokens: [{"old":"/cloud-storage-s3/download","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.download_file_or_folder_in_bucket']['types'],
  },
  'cloud_storage_s_3.stream_download_file_in_bucket_for_launcher': {
    methods: ["GET","HEAD"],
    pattern: '/cloud-storage-s3/launcher/download',
    tokens: [{"old":"/cloud-storage-s3/launcher/download","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/launcher/download","type":0,"val":"launcher","end":""},{"old":"/cloud-storage-s3/launcher/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.stream_download_file_in_bucket_for_launcher']['types'],
  },
  'cloud_storage_s_3.get_presigned_download_url_for_launcher': {
    methods: ["GET","HEAD"],
    pattern: '/cloud-storage-s3/launcher/presign',
    tokens: [{"old":"/cloud-storage-s3/launcher/presign","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/launcher/presign","type":0,"val":"launcher","end":""},{"old":"/cloud-storage-s3/launcher/presign","type":0,"val":"presign","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.get_presigned_download_url_for_launcher']['types'],
  },
  'cloud_storage_s_3.get_presigned_download_urls_for_launcher': {
    methods: ["POST"],
    pattern: '/cloud-storage-s3/launcher/presign/batch',
    tokens: [{"old":"/cloud-storage-s3/launcher/presign/batch","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/launcher/presign/batch","type":0,"val":"launcher","end":""},{"old":"/cloud-storage-s3/launcher/presign/batch","type":0,"val":"presign","end":""},{"old":"/cloud-storage-s3/launcher/presign/batch","type":0,"val":"batch","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.get_presigned_download_urls_for_launcher']['types'],
  },
  'cloud_storage_s_3.delete_in_bucket_and_db': {
    methods: ["POST"],
    pattern: '/cloud-storage-s3/delete',
    tokens: [{"old":"/cloud-storage-s3/delete","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.delete_in_bucket_and_db']['types'],
  },
  'cloud_storage_s_3.get_total_size_file_or_folder_in_bucket': {
    methods: ["POST"],
    pattern: '/cloud-storage-s3/file-or-folder/size',
    tokens: [{"old":"/cloud-storage-s3/file-or-folder/size","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/file-or-folder/size","type":0,"val":"file-or-folder","end":""},{"old":"/cloud-storage-s3/file-or-folder/size","type":0,"val":"size","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.get_total_size_file_or_folder_in_bucket']['types'],
  },
  'cloud_storage_s_3.get_file_content_in_bucket': {
    methods: ["POST"],
    pattern: '/cloud-storage-s3/content',
    tokens: [{"old":"/cloud-storage-s3/content","type":0,"val":"cloud-storage-s3","end":""},{"old":"/cloud-storage-s3/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['cloud_storage_s_3.get_file_content_in_bucket']['types'],
  },
  'game_binary.get_game_binary_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/game-binary/:id',
    tokens: [{"old":"/game-binary/:id","type":0,"val":"game-binary","end":""},{"old":"/game-binary/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['game_binary.get_game_binary_by_id']['types'],
  },
  'game_binary.create_game_binary': {
    methods: ["POST"],
    pattern: '/game-binary',
    tokens: [{"old":"/game-binary","type":0,"val":"game-binary","end":""}],
    types: placeholder as Registry['game_binary.create_game_binary']['types'],
  },
  'game_binary.update_game_binary': {
    methods: ["PUT"],
    pattern: '/game-binary/:id',
    tokens: [{"old":"/game-binary/:id","type":0,"val":"game-binary","end":""},{"old":"/game-binary/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['game_binary.update_game_binary']['types'],
  },
  'game_binary.delete_game_binary': {
    methods: ["DELETE"],
    pattern: '/game-binary/:id',
    tokens: [{"old":"/game-binary/:id","type":0,"val":"game-binary","end":""},{"old":"/game-binary/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['game_binary.delete_game_binary']['types'],
  },
  'game_binary_assignments.get_all_game_binary_assignment_by_game_id': {
    methods: ["GET","HEAD"],
    pattern: '/game/:gameId/binaries',
    tokens: [{"old":"/game/:gameId/binaries","type":0,"val":"game","end":""},{"old":"/game/:gameId/binaries","type":1,"val":"gameId","end":""},{"old":"/game/:gameId/binaries","type":0,"val":"binaries","end":""}],
    types: placeholder as Registry['game_binary_assignments.get_all_game_binary_assignment_by_game_id']['types'],
  },
  'game_categories.get_all_game_categories': {
    methods: ["GET","HEAD"],
    pattern: '/game-categories',
    tokens: [{"old":"/game-categories","type":0,"val":"game-categories","end":""}],
    types: placeholder as Registry['game_categories.get_all_game_categories']['types'],
  },
  'game_category_assignments.get_all_game_category_assignment_by_game_id': {
    methods: ["GET","HEAD"],
    pattern: '/game/:gameId/categories',
    tokens: [{"old":"/game/:gameId/categories","type":0,"val":"game","end":""},{"old":"/game/:gameId/categories","type":1,"val":"gameId","end":""},{"old":"/game/:gameId/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['game_category_assignments.get_all_game_category_assignment_by_game_id']['types'],
  },
  'game_category_assignments.get_all_game_category_assignment_by_category_id': {
    methods: ["GET","HEAD"],
    pattern: '/game/categories/:categoryId',
    tokens: [{"old":"/game/categories/:categoryId","type":0,"val":"game","end":""},{"old":"/game/categories/:categoryId","type":0,"val":"categories","end":""},{"old":"/game/categories/:categoryId","type":1,"val":"categoryId","end":""}],
    types: placeholder as Registry['game_category_assignments.get_all_game_category_assignment_by_category_id']['types'],
  },
  'game_change_logs.create_game_change_log': {
    methods: ["POST"],
    pattern: '/game-change-log',
    tokens: [{"old":"/game-change-log","type":0,"val":"game-change-log","end":""}],
    types: placeholder as Registry['game_change_logs.create_game_change_log']['types'],
  },
  'game_change_logs.update_game_change_log': {
    methods: ["PUT"],
    pattern: '/game-change-log/:id',
    tokens: [{"old":"/game-change-log/:id","type":0,"val":"game-change-log","end":""},{"old":"/game-change-log/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['game_change_logs.update_game_change_log']['types'],
  },
  'game_change_logs.delete_game_change_log': {
    methods: ["DELETE"],
    pattern: '/game-change-log/:id',
    tokens: [{"old":"/game-change-log/:id","type":0,"val":"game-change-log","end":""},{"old":"/game-change-log/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['game_change_logs.delete_game_change_log']['types'],
  },
  'game_change_logs.get_all_game_change_logs': {
    methods: ["GET","HEAD"],
    pattern: '/game-change-logs',
    tokens: [{"old":"/game-change-logs","type":0,"val":"game-change-logs","end":""}],
    types: placeholder as Registry['game_change_logs.get_all_game_change_logs']['types'],
  },
  'game_change_logs.get_all_game_change_log_by_game_id': {
    methods: ["GET","HEAD"],
    pattern: '/game-change-logs/game/:gameId',
    tokens: [{"old":"/game-change-logs/game/:gameId","type":0,"val":"game-change-logs","end":""},{"old":"/game-change-logs/game/:gameId","type":0,"val":"game","end":""},{"old":"/game-change-logs/game/:gameId","type":1,"val":"gameId","end":""}],
    types: placeholder as Registry['game_change_logs.get_all_game_change_log_by_game_id']['types'],
  },
  'game_change_logs.get_game_change_log_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/game-change-log/:id',
    tokens: [{"old":"/game-change-log/:id","type":0,"val":"game-change-log","end":""},{"old":"/game-change-log/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['game_change_logs.get_game_change_log_by_id']['types'],
  },
  'game_change_logs.get_all_game_change_log_by_game_title': {
    methods: ["GET","HEAD"],
    pattern: '/game-change-logs/game-title/:title',
    tokens: [{"old":"/game-change-logs/game-title/:title","type":0,"val":"game-change-logs","end":""},{"old":"/game-change-logs/game-title/:title","type":0,"val":"game-title","end":""},{"old":"/game-change-logs/game-title/:title","type":1,"val":"title","end":""}],
    types: placeholder as Registry['game_change_logs.get_all_game_change_log_by_game_title']['types'],
  },
  'game_platform_assignments.get_all_game_platform_assignment_by_game_id': {
    methods: ["GET","HEAD"],
    pattern: '/game/:gameId/platforms',
    tokens: [{"old":"/game/:gameId/platforms","type":0,"val":"game","end":""},{"old":"/game/:gameId/platforms","type":1,"val":"gameId","end":""},{"old":"/game/:gameId/platforms","type":0,"val":"platforms","end":""}],
    types: placeholder as Registry['game_platform_assignments.get_all_game_platform_assignment_by_game_id']['types'],
  },
  'game_platform_assignments.get_all_game_platform_assignment_by_platform_id': {
    methods: ["GET","HEAD"],
    pattern: '/game/platforms/:platformId',
    tokens: [{"old":"/game/platforms/:platformId","type":0,"val":"game","end":""},{"old":"/game/platforms/:platformId","type":0,"val":"platforms","end":""},{"old":"/game/platforms/:platformId","type":1,"val":"platformId","end":""}],
    types: placeholder as Registry['game_platform_assignments.get_all_game_platform_assignment_by_platform_id']['types'],
  },
  'game_platforms.get_all_game_platforms': {
    methods: ["GET","HEAD"],
    pattern: '/game-platforms',
    tokens: [{"old":"/game-platforms","type":0,"val":"game-platforms","end":""}],
    types: placeholder as Registry['game_platforms.get_all_game_platforms']['types'],
  },
  'games.create_games': {
    methods: ["POST"],
    pattern: '/game',
    tokens: [{"old":"/game","type":0,"val":"game","end":""}],
    types: placeholder as Registry['games.create_games']['types'],
  },
  'games.get_games_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/game/:id',
    tokens: [{"old":"/game/:id","type":0,"val":"game","end":""},{"old":"/game/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['games.get_games_by_id']['types'],
  },
  'games.get_all_games_by_title': {
    methods: ["GET","HEAD"],
    pattern: '/games/title/:title',
    tokens: [{"old":"/games/title/:title","type":0,"val":"games","end":""},{"old":"/games/title/:title","type":0,"val":"title","end":""},{"old":"/games/title/:title","type":1,"val":"title","end":""}],
    types: placeholder as Registry['games.get_all_games_by_title']['types'],
  },
  'games.get_game_by_title': {
    methods: ["GET","HEAD"],
    pattern: '/game',
    tokens: [{"old":"/game","type":0,"val":"game","end":""}],
    types: placeholder as Registry['games.get_game_by_title']['types'],
  },
  'games.get_all_games': {
    methods: ["GET","HEAD"],
    pattern: '/games',
    tokens: [{"old":"/games","type":0,"val":"games","end":""}],
    types: placeholder as Registry['games.get_all_games']['types'],
  },
  'games.update_games': {
    methods: ["PUT"],
    pattern: '/game/:id',
    tokens: [{"old":"/game/:id","type":0,"val":"game","end":""},{"old":"/game/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['games.update_games']['types'],
  },
  'games.delete_games': {
    methods: ["DELETE"],
    pattern: '/game/:id',
    tokens: [{"old":"/game/:id","type":0,"val":"game","end":""},{"old":"/game/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['games.delete_games']['types'],
  },
  'game_server.get_all_game_servers': {
    methods: ["GET","HEAD"],
    pattern: '/game-servers',
    tokens: [{"old":"/game-servers","type":0,"val":"game-servers","end":""}],
    types: placeholder as Registry['game_server.get_all_game_servers']['types'],
  },
  'game_server.create_game_server': {
    methods: ["POST"],
    pattern: '/game-servers',
    tokens: [{"old":"/game-servers","type":0,"val":"game-servers","end":""}],
    types: placeholder as Registry['game_server.create_game_server']['types'],
  },
  'game_versions.create_game_version': {
    methods: ["POST"],
    pattern: '/games/:gameId/versions',
    tokens: [{"old":"/games/:gameId/versions","type":0,"val":"games","end":""},{"old":"/games/:gameId/versions","type":1,"val":"gameId","end":""},{"old":"/games/:gameId/versions","type":0,"val":"versions","end":""}],
    types: placeholder as Registry['game_versions.create_game_version']['types'],
  },
  'game_versions.get_all_game_versions_by_game_id': {
    methods: ["GET","HEAD"],
    pattern: '/games/:gameId/versions',
    tokens: [{"old":"/games/:gameId/versions","type":0,"val":"games","end":""},{"old":"/games/:gameId/versions","type":1,"val":"gameId","end":""},{"old":"/games/:gameId/versions","type":0,"val":"versions","end":""}],
    types: placeholder as Registry['game_versions.get_all_game_versions_by_game_id']['types'],
  },
  'game_versions.get_all_game_versions': {
    methods: ["GET","HEAD"],
    pattern: '/games/versions',
    tokens: [{"old":"/games/versions","type":0,"val":"games","end":""},{"old":"/games/versions","type":0,"val":"versions","end":""}],
    types: placeholder as Registry['game_versions.get_all_game_versions']['types'],
  },
  'game_versions.get_game_version': {
    methods: ["GET","HEAD"],
    pattern: '/games/:gameId/versions/:gameVersionId',
    tokens: [{"old":"/games/:gameId/versions/:gameVersionId","type":0,"val":"games","end":""},{"old":"/games/:gameId/versions/:gameVersionId","type":1,"val":"gameId","end":""},{"old":"/games/:gameId/versions/:gameVersionId","type":0,"val":"versions","end":""},{"old":"/games/:gameId/versions/:gameVersionId","type":1,"val":"gameVersionId","end":""}],
    types: placeholder as Registry['game_versions.get_game_version']['types'],
  },
  'game_versions.update_game_version': {
    methods: ["PUT"],
    pattern: '/games/:gameId/versions/:gameVersionId',
    tokens: [{"old":"/games/:gameId/versions/:gameVersionId","type":0,"val":"games","end":""},{"old":"/games/:gameId/versions/:gameVersionId","type":1,"val":"gameId","end":""},{"old":"/games/:gameId/versions/:gameVersionId","type":0,"val":"versions","end":""},{"old":"/games/:gameId/versions/:gameVersionId","type":1,"val":"gameVersionId","end":""}],
    types: placeholder as Registry['game_versions.update_game_version']['types'],
  },
  'game_versions.delete_game_version': {
    methods: ["DELETE"],
    pattern: '/games/:gameId/versions/:gameVersionId',
    tokens: [{"old":"/games/:gameId/versions/:gameVersionId","type":0,"val":"games","end":""},{"old":"/games/:gameId/versions/:gameVersionId","type":1,"val":"gameId","end":""},{"old":"/games/:gameId/versions/:gameVersionId","type":0,"val":"versions","end":""},{"old":"/games/:gameId/versions/:gameVersionId","type":1,"val":"gameVersionId","end":""}],
    types: placeholder as Registry['game_versions.delete_game_version']['types'],
  },
  'game_versions.get_latest_available_version': {
    methods: ["GET","HEAD"],
    pattern: '/games/:gameId/version-latest',
    tokens: [{"old":"/games/:gameId/version-latest","type":0,"val":"games","end":""},{"old":"/games/:gameId/version-latest","type":1,"val":"gameId","end":""},{"old":"/games/:gameId/version-latest","type":0,"val":"version-latest","end":""}],
    types: placeholder as Registry['game_versions.get_latest_available_version']['types'],
  },
  'languages.get_all_languages': {
    methods: ["GET","HEAD"],
    pattern: '/languages',
    tokens: [{"old":"/languages","type":0,"val":"languages","end":""}],
    types: placeholder as Registry['languages.get_all_languages']['types'],
  },
  'launcher_crz.check_is_available_version_launcher': {
    methods: ["GET","HEAD"],
    pattern: '/launcher/updater-manifest/:os/:archSystem/:currentVersion',
    tokens: [{"old":"/launcher/updater-manifest/:os/:archSystem/:currentVersion","type":0,"val":"launcher","end":""},{"old":"/launcher/updater-manifest/:os/:archSystem/:currentVersion","type":0,"val":"updater-manifest","end":""},{"old":"/launcher/updater-manifest/:os/:archSystem/:currentVersion","type":1,"val":"os","end":""},{"old":"/launcher/updater-manifest/:os/:archSystem/:currentVersion","type":1,"val":"archSystem","end":""},{"old":"/launcher/updater-manifest/:os/:archSystem/:currentVersion","type":1,"val":"currentVersion","end":""}],
    types: placeholder as Registry['launcher_crz.check_is_available_version_launcher']['types'],
  },
  'launcher_crz.download_launcher': {
    methods: ["GET","HEAD"],
    pattern: '/launcher/download/:nameBundle',
    tokens: [{"old":"/launcher/download/:nameBundle","type":0,"val":"launcher","end":""},{"old":"/launcher/download/:nameBundle","type":0,"val":"download","end":""},{"old":"/launcher/download/:nameBundle","type":1,"val":"nameBundle","end":""}],
    types: placeholder as Registry['launcher_crz.download_launcher']['types'],
  },
  'maintenance_web_site.update_is_maintenance': {
    methods: ["PUT"],
    pattern: '/maintenance-websites/is-maintenance',
    tokens: [{"old":"/maintenance-websites/is-maintenance","type":0,"val":"maintenance-websites","end":""},{"old":"/maintenance-websites/is-maintenance","type":0,"val":"is-maintenance","end":""}],
    types: placeholder as Registry['maintenance_web_site.update_is_maintenance']['types'],
  },
  'maintenance_web_site.is_maintenance': {
    methods: ["GET","HEAD"],
    pattern: '/maintenance-websites/is-maintenance',
    tokens: [{"old":"/maintenance-websites/is-maintenance","type":0,"val":"maintenance-websites","end":""},{"old":"/maintenance-websites/is-maintenance","type":0,"val":"is-maintenance","end":""}],
    types: placeholder as Registry['maintenance_web_site.is_maintenance']['types'],
  },
  'nats.publish': {
    methods: ["POST"],
    pattern: '/publish',
    tokens: [{"old":"/publish","type":0,"val":"publish","end":""}],
    types: placeholder as Registry['nats.publish']['types'],
  },
  'nats.subscribe': {
    methods: ["POST"],
    pattern: '/subscribe',
    tokens: [{"old":"/subscribe","type":0,"val":"subscribe","end":""}],
    types: placeholder as Registry['nats.subscribe']['types'],
  },
  'order_product.create_order_product': {
    methods: ["POST"],
    pattern: '/order-products',
    tokens: [{"old":"/order-products","type":0,"val":"order-products","end":""}],
    types: placeholder as Registry['order_product.create_order_product']['types'],
  },
  'order_product.update_order_product': {
    methods: ["PUT"],
    pattern: '/order-products/:id',
    tokens: [{"old":"/order-products/:id","type":0,"val":"order-products","end":""},{"old":"/order-products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['order_product.update_order_product']['types'],
  },
  'order_product.delete_order_product': {
    methods: ["DELETE"],
    pattern: '/order-products/:id',
    tokens: [{"old":"/order-products/:id","type":0,"val":"order-products","end":""},{"old":"/order-products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['order_product.delete_order_product']['types'],
  },
  'order_product.get_all_order_products_by_order_id': {
    methods: ["GET","HEAD"],
    pattern: '/order-products/order/:orders_id',
    tokens: [{"old":"/order-products/order/:orders_id","type":0,"val":"order-products","end":""},{"old":"/order-products/order/:orders_id","type":0,"val":"order","end":""},{"old":"/order-products/order/:orders_id","type":1,"val":"orders_id","end":""}],
    types: placeholder as Registry['order_product.get_all_order_products_by_order_id']['types'],
  },
  'order.create_order': {
    methods: ["POST"],
    pattern: '/orders',
    tokens: [{"old":"/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['order.create_order']['types'],
  },
  'order.update_order': {
    methods: ["PUT"],
    pattern: '/orders/:id',
    tokens: [{"old":"/orders/:id","type":0,"val":"orders","end":""},{"old":"/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['order.update_order']['types'],
  },
  'order.delete_order': {
    methods: ["DELETE"],
    pattern: '/orders/:id',
    tokens: [{"old":"/orders/:id","type":0,"val":"orders","end":""},{"old":"/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['order.delete_order']['types'],
  },
  'order.get_all_orders_by_user_id': {
    methods: ["GET","HEAD"],
    pattern: '/orders/user/:users_id',
    tokens: [{"old":"/orders/user/:users_id","type":0,"val":"orders","end":""},{"old":"/orders/user/:users_id","type":0,"val":"user","end":""},{"old":"/orders/user/:users_id","type":1,"val":"users_id","end":""}],
    types: placeholder as Registry['order.get_all_orders_by_user_id']['types'],
  },
  'order.get_order_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/orders/:id',
    tokens: [{"old":"/orders/:id","type":0,"val":"orders","end":""},{"old":"/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['order.get_order_by_id']['types'],
  },
  'product_category.get_all_product_categories': {
    methods: ["GET","HEAD"],
    pattern: '/product-categories',
    tokens: [{"old":"/product-categories","type":0,"val":"product-categories","end":""}],
    types: placeholder as Registry['product_category.get_all_product_categories']['types'],
  },
  'product_discount.create_product_discount': {
    methods: ["POST"],
    pattern: '/product-discounts',
    tokens: [{"old":"/product-discounts","type":0,"val":"product-discounts","end":""}],
    types: placeholder as Registry['product_discount.create_product_discount']['types'],
  },
  'product_discount.get_product_discount_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/product-discounts/:id',
    tokens: [{"old":"/product-discounts/:id","type":0,"val":"product-discounts","end":""},{"old":"/product-discounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['product_discount.get_product_discount_by_id']['types'],
  },
  'product_discount.get_all_product_discounts_by_product_id': {
    methods: ["GET","HEAD"],
    pattern: '/product-discounts/product/:productId',
    tokens: [{"old":"/product-discounts/product/:productId","type":0,"val":"product-discounts","end":""},{"old":"/product-discounts/product/:productId","type":0,"val":"product","end":""},{"old":"/product-discounts/product/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['product_discount.get_all_product_discounts_by_product_id']['types'],
  },
  'product_discount.update_product_discount': {
    methods: ["PUT"],
    pattern: '/product-discounts/:id',
    tokens: [{"old":"/product-discounts/:id","type":0,"val":"product-discounts","end":""},{"old":"/product-discounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['product_discount.update_product_discount']['types'],
  },
  'product_discount.delete_product_discount': {
    methods: ["DELETE"],
    pattern: '/product-discounts/:id',
    tokens: [{"old":"/product-discounts/:id","type":0,"val":"product-discounts","end":""},{"old":"/product-discounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['product_discount.delete_product_discount']['types'],
  },
  'product_game_server.get_all_product_game_servers': {
    methods: ["GET","HEAD"],
    pattern: '/product-game-servers',
    tokens: [{"old":"/product-game-servers","type":0,"val":"product-game-servers","end":""}],
    types: placeholder as Registry['product_game_server.get_all_product_game_servers']['types'],
  },
  'product_game_server.create_product_game_server': {
    methods: ["POST"],
    pattern: '/product-game-servers',
    tokens: [{"old":"/product-game-servers","type":0,"val":"product-game-servers","end":""}],
    types: placeholder as Registry['product_game_server.create_product_game_server']['types'],
  },
  'product.create_product': {
    methods: ["POST"],
    pattern: '/products',
    tokens: [{"old":"/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['product.create_product']['types'],
  },
  'product.get_product_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/products/:id',
    tokens: [{"old":"/products/:id","type":0,"val":"products","end":""},{"old":"/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['product.get_product_by_id']['types'],
  },
  'product.get_all_products': {
    methods: ["GET","HEAD"],
    pattern: '/products',
    tokens: [{"old":"/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['product.get_all_products']['types'],
  },
  'product.get_product_by_name': {
    methods: ["GET","HEAD"],
    pattern: '/products/name/:name',
    tokens: [{"old":"/products/name/:name","type":0,"val":"products","end":""},{"old":"/products/name/:name","type":0,"val":"name","end":""},{"old":"/products/name/:name","type":1,"val":"name","end":""}],
    types: placeholder as Registry['product.get_product_by_name']['types'],
  },
  'product.update_product': {
    methods: ["PUT"],
    pattern: '/products/:id',
    tokens: [{"old":"/products/:id","type":0,"val":"products","end":""},{"old":"/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['product.update_product']['types'],
  },
  'product.delete_product': {
    methods: ["DELETE"],
    pattern: '/products/:id',
    tokens: [{"old":"/products/:id","type":0,"val":"products","end":""},{"old":"/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['product.delete_product']['types'],
  },
  'product.get_game_product_paid_and_owned': {
    methods: ["GET","HEAD"],
    pattern: '/products/games/:gameId/paid-and-owned',
    tokens: [{"old":"/products/games/:gameId/paid-and-owned","type":0,"val":"products","end":""},{"old":"/products/games/:gameId/paid-and-owned","type":0,"val":"games","end":""},{"old":"/products/games/:gameId/paid-and-owned","type":1,"val":"gameId","end":""},{"old":"/products/games/:gameId/paid-and-owned","type":0,"val":"paid-and-owned","end":""}],
    types: placeholder as Registry['product.get_game_product_paid_and_owned']['types'],
  },
  'product.get_all_games_products_paid_and_owned': {
    methods: ["GET","HEAD"],
    pattern: '/products/games/paid-and-owned',
    tokens: [{"old":"/products/games/paid-and-owned","type":0,"val":"products","end":""},{"old":"/products/games/paid-and-owned","type":0,"val":"games","end":""},{"old":"/products/games/paid-and-owned","type":0,"val":"paid-and-owned","end":""}],
    types: placeholder as Registry['product.get_all_games_products_paid_and_owned']['types'],
  },
  'seatyrants.get_info_user': {
    methods: ["GET","HEAD"],
    pattern: '/seatyrants/info-user',
    tokens: [{"old":"/seatyrants/info-user","type":0,"val":"seatyrants","end":""},{"old":"/seatyrants/info-user","type":0,"val":"info-user","end":""}],
    types: placeholder as Registry['seatyrants.get_info_user']['types'],
  },
  'stripe.create_payment_intent_stripe': {
    methods: ["POST"],
    pattern: '/stripe/create-payment-intent',
    tokens: [{"old":"/stripe/create-payment-intent","type":0,"val":"stripe","end":""},{"old":"/stripe/create-payment-intent","type":0,"val":"create-payment-intent","end":""}],
    types: placeholder as Registry['stripe.create_payment_intent_stripe']['types'],
  },
  'stripe.check_proxy_vpn': {
    methods: ["POST"],
    pattern: '/proxy-check-io',
    tokens: [{"old":"/proxy-check-io","type":0,"val":"proxy-check-io","end":""}],
    types: placeholder as Registry['stripe.check_proxy_vpn']['types'],
  },
  'stripe.handle_webhook_stripe': {
    methods: ["POST"],
    pattern: '/stripe/webhooks',
    tokens: [{"old":"/stripe/webhooks","type":0,"val":"stripe","end":""},{"old":"/stripe/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['stripe.handle_webhook_stripe']['types'],
  },
  'ticket_categories.get_all_ticket_categories': {
    methods: ["GET","HEAD"],
    pattern: '/ticket-categories',
    tokens: [{"old":"/ticket-categories","type":0,"val":"ticket-categories","end":""}],
    types: placeholder as Registry['ticket_categories.get_all_ticket_categories']['types'],
  },
  'ticket_responses.create_ticket_responses': {
    methods: ["POST"],
    pattern: '/ticket-response',
    tokens: [{"old":"/ticket-response","type":0,"val":"ticket-response","end":""}],
    types: placeholder as Registry['ticket_responses.create_ticket_responses']['types'],
  },
  'ticket_responses.get_all_tickets_responses_by_ticket_id': {
    methods: ["GET","HEAD"],
    pattern: '/ticket-response/:ticketId',
    tokens: [{"old":"/ticket-response/:ticketId","type":0,"val":"ticket-response","end":""},{"old":"/ticket-response/:ticketId","type":1,"val":"ticketId","end":""}],
    types: placeholder as Registry['ticket_responses.get_all_tickets_responses_by_ticket_id']['types'],
  },
  'tickets.create_tickets': {
    methods: ["POST"],
    pattern: '/ticket',
    tokens: [{"old":"/ticket","type":0,"val":"ticket","end":""}],
    types: placeholder as Registry['tickets.create_tickets']['types'],
  },
  'tickets.get_tickets_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/ticket/:id',
    tokens: [{"old":"/ticket/:id","type":0,"val":"ticket","end":""},{"old":"/ticket/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tickets.get_tickets_by_id']['types'],
  },
  'tickets.get_all_tickets': {
    methods: ["GET","HEAD"],
    pattern: '/tickets',
    tokens: [{"old":"/tickets","type":0,"val":"tickets","end":""}],
    types: placeholder as Registry['tickets.get_all_tickets']['types'],
  },
  'tickets.get_all_tickets_by_user_id': {
    methods: ["GET","HEAD"],
    pattern: '/tickets/:userId',
    tokens: [{"old":"/tickets/:userId","type":0,"val":"tickets","end":""},{"old":"/tickets/:userId","type":1,"val":"userId","end":""}],
    types: placeholder as Registry['tickets.get_all_tickets_by_user_id']['types'],
  },
  'tickets.update_ticket_by_id_for_status': {
    methods: ["PUT"],
    pattern: '/tickets/:id',
    tokens: [{"old":"/tickets/:id","type":0,"val":"tickets","end":""},{"old":"/tickets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tickets.update_ticket_by_id_for_status']['types'],
  },
  'tickets.get_tickets_count_by_status_open_for_user': {
    methods: ["GET","HEAD"],
    pattern: '/tickets-open-count/:userId',
    tokens: [{"old":"/tickets-open-count/:userId","type":0,"val":"tickets-open-count","end":""},{"old":"/tickets-open-count/:userId","type":1,"val":"userId","end":""}],
    types: placeholder as Registry['tickets.get_tickets_count_by_status_open_for_user']['types'],
  },
  'ticket_statuses.get_all_ticket_statuses': {
    methods: ["GET","HEAD"],
    pattern: '/ticket-statuses',
    tokens: [{"old":"/ticket-statuses","type":0,"val":"ticket-statuses","end":""}],
    types: placeholder as Registry['ticket_statuses.get_all_ticket_statuses']['types'],
  },
  'user_game_libraries.get_all_users_games_libraries_by_user_id': {
    methods: ["GET","HEAD"],
    pattern: '/user-game-libraries/:userId',
    tokens: [{"old":"/user-game-libraries/:userId","type":0,"val":"user-game-libraries","end":""},{"old":"/user-game-libraries/:userId","type":1,"val":"userId","end":""}],
    types: placeholder as Registry['user_game_libraries.get_all_users_games_libraries_by_user_id']['types'],
  },
  'user_game_libraries.add_game_to_user_game_libraries': {
    methods: ["POST"],
    pattern: '/user-game-libraries',
    tokens: [{"old":"/user-game-libraries","type":0,"val":"user-game-libraries","end":""}],
    types: placeholder as Registry['user_game_libraries.add_game_to_user_game_libraries']['types'],
  },
  'user_roles.get_all_user_roles': {
    methods: ["GET","HEAD"],
    pattern: '/user-roles',
    tokens: [{"old":"/user-roles","type":0,"val":"user-roles","end":""}],
    types: placeholder as Registry['user_roles.get_all_user_roles']['types'],
  },
  'users.decode_token_return_user': {
    methods: ["GET","HEAD"],
    pattern: '/user',
    tokens: [{"old":"/user","type":0,"val":"user","end":""}],
    types: placeholder as Registry['users.decode_token_return_user']['types'],
  },
  'users.get_vars_environment_for_user': {
    methods: ["GET","HEAD"],
    pattern: '/user/sensitive-data',
    tokens: [{"old":"/user/sensitive-data","type":0,"val":"user","end":""},{"old":"/user/sensitive-data","type":0,"val":"sensitive-data","end":""}],
    types: placeholder as Registry['users.get_vars_environment_for_user']['types'],
  },
  'users.get_users_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/user/:id',
    tokens: [{"old":"/user/:id","type":0,"val":"user","end":""},{"old":"/user/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.get_users_by_id']['types'],
  },
  'users.get_all_users': {
    methods: ["GET","HEAD"],
    pattern: '/users',
    tokens: [{"old":"/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.get_all_users']['types'],
  },
  'users.get_all_users_by_username_or_email': {
    methods: ["GET","HEAD"],
    pattern: '/users/by-username-or-email/:usernameOrEmail',
    tokens: [{"old":"/users/by-username-or-email/:usernameOrEmail","type":0,"val":"users","end":""},{"old":"/users/by-username-or-email/:usernameOrEmail","type":0,"val":"by-username-or-email","end":""},{"old":"/users/by-username-or-email/:usernameOrEmail","type":1,"val":"usernameOrEmail","end":""}],
    types: placeholder as Registry['users.get_all_users_by_username_or_email']['types'],
  },
  'users.update_users': {
    methods: ["PUT"],
    pattern: '/user/:id',
    tokens: [{"old":"/user/:id","type":0,"val":"user","end":""},{"old":"/user/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.update_users']['types'],
  },
  'users.delete_users': {
    methods: ["DELETE"],
    pattern: '/user/:id',
    tokens: [{"old":"/user/:id","type":0,"val":"user","end":""},{"old":"/user/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.delete_users']['types'],
  },
  'users.update_users_role': {
    methods: ["PUT"],
    pattern: '/user/:userId/role/:roleId',
    tokens: [{"old":"/user/:userId/role/:roleId","type":0,"val":"user","end":""},{"old":"/user/:userId/role/:roleId","type":1,"val":"userId","end":""},{"old":"/user/:userId/role/:roleId","type":0,"val":"role","end":""},{"old":"/user/:userId/role/:roleId","type":1,"val":"roleId","end":""}],
    types: placeholder as Registry['users.update_users_role']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
