apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-crzgames-website-backend-hpa
  namespace: prod-crzgames-website-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-crzgames-website-backend-deployment
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50
