apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-crzgames-website-backend-ingress
  namespace: prod-crzgames-website-backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/enable-real-ip: 'true'
    nginx.ingress.kubernetes.io/forwarded-for-header: 'X-Forwarded-For'
    nginx.ingress.kubernetes.io/use-forwarded-headers: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.crzcommon.com
      secretName: prod-api-crzcommon-tls
  rules:
    - host: api.crzcommon.com
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: prod-crzgames-website-backend-service
                port:
                  number: 3333
